### PR TITLE
The-Newseek-Milestone1

### PR DESCRIPTION
**Pull request by Anvi98**
In this first milestone, we prepared the tools to develop this website and we created 2 small sections and we: 

- Set up a new the repository

- Prepared the main HTML file

- Installed Bootstrap in your project

- Prepared your project to work with 3 screen sizes: mobile, tablet, and desktop using the Bootstrap responsive grid classes

### CODE REVIEW

**Review by rukundoeric — CHANGES_REQUESTED** [review]
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are few issues we need to address before we move on, please check the comments below._

- ### To Highlight
  - [x] N/A

- ### To Improve
  - [x] [MANDATORY] Your `SUBSCRIBE` button is not quite similar to the original, kindly fix that.
  - [x] [MANDATORY] The margin of your `HEADER` and `FOTTER` is not quite similar to the original, kindly fix that.
  - [x] [MANDATORY] Your second link section does not much with the original, kindly fix that.
  - [x] [MANDATORY] And don't forget to fix the merge conflict before your request another code review.

_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on Slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
Slack: Rukundo Eric**

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @Anvi98 & @errea**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [x] when you hide the navbar in the tablet and mobile views, make sure to remove the white space in their place.
- [x]  you should have only two breakpoints, one for tablet and one for mobile view, right now your header and main navbar have two different breakpoints, meaning that they don't resize on the same widths. please make sure to fix this.



---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Review by SmithVyne — CHANGES_REQUESTED** [review]
### Changes Required 🤕 👍 
Hello, you have made some decent progress on this project but you need to make a few additional improvements to get it approved.

You navbar(Mobile view):
image

Navbar from the snapshot (Mobile view):
image

Also, I can see your logo is very large on tablet and mobile, try to make your design match the snapshot as close as possible. You will learn a lot in the process. 

Make these changes and request another code review. You should get it approved this time.

You can also reach out to me on slack, **@SmithVyne** if you have any other questions.

**Review by addod19 — APPROVED** [review]
## Status: Approved :trophy: :balloon: 

Hi @Anvi98 and @errea, congratulations on this project :+1: Having fixed the responsiveness of the app :muscle: I hereby approve the project :fireworks: 

Kindly go ahead and merge into development, do not forget to submit the project completion form
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by errea** [comment]
Good Job coding Patner 🏆 🎈
Nice Collaboration @Anvi98  👏 💯 👍
Lets Keep working hard.
Happy Coding😃

**Pull request merged**
